[package]
name = "eid-agent-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
openssl = "0.10.66"
ring = { version = "0.17.8", features = ["std"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
untrusted = "0.9.0"
